name: Update Local Repo On Push

on:
  push:
    branches:
      - main # Change to your default branch

jobs:
  update-local-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Local Repo
        run: |
          git fetch origin
          git reset --hard origin/main
